version: '3.9'

services:
  redis-server:
    image: redis:latest # Používá oficiální Redis image z Docker Hubu
    container_name: redis-server
    ports:
      - "6379:6379" # Mapuje port 6379 (výchozí Redis port) z kontejneru na hostitelský stroj
    volumes:
      - redis-data:/data # Připojuje volume pro perzistenci dat (viz níže)
    # Pro konfiguraci Redis (nepovinné, ale užitečné pro pokročilejší nastavení):
    # command: redis-server /usr/local/etc/redis/redis.conf
    # volumes:
    #   - ./redis.conf:/usr/local/etc/redis/redis.conf # Mapuje vlastní konfigurační soubor
    restart: always # Restartuje kontejner v případě pádu.

volumes:
  redis-data:
    # Definuje pojmenované volume pro ukládání Redis dat.
    #  driver: local # Volitelné: specifikace driveru pro volume (výchozí je 'local').
