 version: "3.9"
 services:
   web:
     image: nginx:latest
     ports:
       - "8080:80"
     volumes:
       - ./index.html:/usr/share/nginx/html/index.html
       - ./data.json:/usr/share/nginx/html/data.json 