version: "3.9"
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes # Přijetí licence.
    volumes:
      - neo4j-data:/data # Volitelné: Připojení složky pro perzistenci dat.

volumes:
  neo4j-data:
